alias e='nvim'
alias v='nvim'
alias r='ruby'
alias g='git'
alias d='docker'
alias cr='crystal'
alias ll='ls -lAh'
alias df='df -m'
alias gst='git st'
alias gad='git add'
alias gdi='git di'

alias bi="bundle install"
alias bu='bundle update'
alias be='bundle exec'
alias dums='du -m | sort -n'
